# Generated by Django 5.2.13 on 2026-04-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_uid', models.CharField(max_length=128, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(choices=[('Student', 'Estudiante'), ('Teacher', 'Docente'), ('Admin', 'Admin')], default='Student', max_length=20)),
                ('university', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'ordering': ['display_name'],
            },
        ),
    ]
