# Generated by Django 6.0.3 on 2026-04-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_uid', models.CharField(help_text='UID del usuario en Firebase Authentication', max_length=128)),
                ('text', models.TextField(help_text='Texto de la pregunta')),
                ('session_name', models.CharField(blank=True, default='', help_text='Nombre de la clase o sesión', max_length=200)),
                ('was_spoken', models.BooleanField(default=False, help_text='Indica si la pregunta fue reproducida con voz sintética')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['-created_at'],
            },
        ),
    ]
