# Generated by Django 6.0.4 on 2026-04-11 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_uid', models.CharField(help_text='UID del docente en Firebase Authentication', max_length=128)),
                ('title', models.CharField(help_text='Título del video', max_length=300)),
                ('video_file', models.FileField(help_text='Archivo de video subido', upload_to='videos/%Y/%m/')),
                ('duration', models.FloatField(blank=True, help_text='Duración del video en segundos', null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Subido'), ('processing', 'Procesando'), ('completed', 'Completado'), ('published', 'Publicado'), ('error', 'Error')], default='uploaded', help_text='Estado actual del procesamiento', max_length=20)),
                ('language', models.CharField(default='es', help_text='Idioma del audio (código ISO-639-1)', max_length=10)),
                ('error_message', models.TextField(blank=True, default='', help_text='Mensaje de error si la transcripción falló')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(help_text='Número de orden del segmento (1, 2, 3...)')),
                ('start_time', models.FloatField(help_text='Tiempo de inicio en segundos')),
                ('end_time', models.FloatField(help_text='Tiempo de fin en segundos')),
                ('text', models.TextField(help_text='Texto del subtítulo')),
                ('is_edited', models.BooleanField(default=False, help_text='Indica si fue editado manualmente por el docente')),
                ('video', models.ForeignKey(help_text='Video al que pertenece este subtítulo', on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='questions.video')),
            ],
            options={
                'verbose_name': 'Subtítulo',
                'verbose_name_plural': 'Subtítulos',
                'ordering': ['video', 'index'],
                'unique_together': {('video', 'index')},
            },
        ),
    ]
