[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate && gunicorn iris_backend.wsgi --log-file -"
healthcheckPath = "/api/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
