# Generated by Django 5.2.13 on 2026-04-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_uid', models.CharField(help_text='firebase_uid del docente', max_length=128)),
                ('session_name', models.CharField(blank=True, default='', max_length=200)),
                ('transcript', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sesión de Transcripción',
                'ordering': ['-created_at'],
            },
        ),
    ]
