# Generated by Django 5.2.13 on 2026-04-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('emergency', 'Emergencia')], default='info', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, help_text='firebase_uid del admin', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alerta de Emergencia',
                'ordering': ['-created_at'],
            },
        ),
    ]
